services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance_pipeline
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finance_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 5

  seed:
    build: ./seed
    depends_on:
      db:
        condition: service_healthy
    environment:
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      DATABASE_URL: postgresql://admin:admin@db:5432/finance_pipeline

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/finance_pipeline
      FINNHUB_API_KEY: d3l4jg9r01qp3ucqdet0d3l4jg9r01qp3ucqdetg
    ports:
      - "8501:8501"
    command: >
      sh -c "
        python -u stream_listener.py &
        streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: